/**
 * iCALLOG V18 - Master Explicit & Unrestricted Studio Engine
 * Provides comprehensive genre support (General & Non-General / Mature / Unrestricted)
 * across Image, Film, Video, Image+Video, and 3D Engines.
 * 
 * Includes Creator Free Override for designated master creators.
 */

import { UserProfile } from '../types.ts';

export type StudioTarget = 'image' | 'film' | 'video' | 'image_video' | '3d';

export interface ExplicitGenre {
  id: string;
  name: string;
  hindiName: string;
  category: 'general' | 'non_general' | 'all_over_world' | 'indian_bollywood';
  badge: string;
  emoji: string;
  color: string;
  bgLight: string;
  borderColor: string;
  description: string;
  hindiDesc: string;
  targetStudios: StudioTarget[];
  is18Plus: boolean;
  promptModifiers: {
    image: string;
    film: string;
    video: string;
    image_video: string;
    threeD: string;
  };
  presets: string[];
}

/**
 * Check if the user has 100% Free Lifetime Creator Override
 */
export function isUserExplicitFree(user?: UserProfile | null): boolean {
  if (!user) return false;
  const email = (user.email || '').toLowerCase().trim();
  const name = (user.name || '').toLowerCase();
  
  if (
    email === 'jayupadhyay2857@gmail.com' ||
    user.role === 'creator_override' ||
    user.role === 'admin' ||
    user.explicitAccessMode === 'free_creator' ||
    name.includes('jay')
  ) {
    return true;
  }
  return false;
}

/**
 * Check if user has permission to use Explicit / Unrestricted features
 */
export function canAccessExplicit(user?: UserProfile | null): boolean {
  if (!user) return false;
  if (isUserExplicitFree(user)) return true;
  if (user.vipTier === 'diamond' || user.vipTier === 'gold' || user.isExplicitUnlocked === true) {
    return true;
  }
  return false;
}

/**
 * All Genres (General & Non-General / Mature / Explicit)
 */
export const EXPLICIT_GENRES: ExplicitGenre[] = [
  // --- GENERAL GENRES ---
  {
    id: 'cinematic_hyperrealism',
    name: 'Hollywood Cinematic Hyperrealism',
    hindiName: 'सिनेमैटिक 8K रियलिज्म',
    category: 'general',
    badge: 'Cinematic 8K',
    emoji: '🎬',
    color: '#38bdf8',
    bgLight: 'bg-sky-500/10',
    borderColor: 'border-sky-500/30',
    description: 'Ultra-detailed 35mm Arri Alexa cinematography, anamorphic lens flare, photorealistic studio lighting.',
    hindiDesc: 'हॉलीवुड स्तर का 8K सिनेमैटिक रियलिज्म और विस्तृत प्रकाश व्यवस्था।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'cinematic shot, 35mm anamorphic lens, Arri Alexa 8K, Kodak Vision3 500T, volumetric lighting, photorealistic subsurface scattering, masterpiece',
      film: 'SCENE DIRECTION: High cinematic fidelity, moody chiaroscuro lighting, slow dolly zoom, orchestral score swells, hyper-realistic emotional tension.',
      video: '8k cinematic hyper-realism, 60fps steadycam gimbal sweep, dynamic range HDR, organic depth of field, blockbuster quality.',
      image_video: 'seamless cinematic morphing, photorealistic lighting blending, film grain integration, volumetric fog overlay.',
      threeD: 'PBR 8K textures, ray-traced subsurface scattering, physically accurate ambient occlusion, realistic normal mapping.',
    },
    presets: ['Anamorphic Sunset 8K', 'IMAX Action Sweep', 'Noir Shadow Lighting', 'Studio Beauty Glow'],
  },
  {
    id: 'cyberpunk_neon',
    name: 'Cyberpunk 2077 Neon & Dystopia',
    hindiName: 'साइबरपंक नियॉन व हाई-टेक',
    category: 'general',
    badge: 'Cyberpunk',
    emoji: '🏙️',
    color: '#06b6d4',
    bgLight: 'bg-cyan-500/10',
    borderColor: 'border-cyan-500/30',
    description: 'Futuristic rainy megacity, neon holograms, glowing cyborg cyberware, chrome reflections.',
    hindiDesc: 'भविष्यवादी नियॉन शहर, रोबोटिक्स और साइबोर्ग एस्थेटिक्स।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'cyberpunk neon aesthetic, wet asphalt reflections, glowing cybernetic augmentations, holographic billboards, synthwave atmosphere, 8k render',
      film: 'SCENE DIRECTION: Neon-soaked alleyway, pouring rain hitting chrome armor, synth bass reverberation, cyber-hacker tense confrontation.',
      video: 'high speed neon light trails, glitch video transitions, robotic motion tracking, cybernetic optic flare, 4k 60fps.',
      image_video: 'holographic layer fusion, neon chromatic aberration, cyber grid composite, glitch audio-sync.',
      threeD: 'emissive neon materials, metallic chrome shaders, robotic joint mechanics, cybernetic wire rigging.',
    },
    presets: ['Night City Rain', 'Chrome Android Rig', 'Hologram Blade Runner', 'Neon Alley Chase'],
  },
  {
    id: 'anime_epic',
    name: 'Japanese Anime & Manga Masterpiece',
    hindiName: 'एनीमे व मांगा एपिक',
    category: 'general',
    badge: 'Anime Epic',
    emoji: '⚡',
    color: '#ec4899',
    bgLight: 'bg-pink-500/10',
    borderColor: 'border-pink-500/30',
    description: 'Makoto Shinkai & Studio Ufotable aesthetic, vibrant celestial skies, high dynamic anime shading.',
    hindiDesc: 'माकोतो शिंकाई और उफ़ोटेबल स्टाइल का एनीमेशन व विज़ुअल्स।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'masterpiece anime key visual, Studio Ufotable style, cel-shaded, vibrant twilight sky, floating light particles, sharp line art, 8k',
      film: 'SCENE DIRECTION: Dramatic anime wind gust, eyes glowing with supernatural energy, epic shonen battle monologue, orchestral climax.',
      video: 'fluid 2D/3D anime combat motion, speed-lines camera track, particle energy explosions, 60fps anime choreography.',
      image_video: 'manga halftone overlay, anime speedburst transition, celestial sky fusion, cel-shaded color grade.',
      threeD: 'toon shader outlines, anime stylized hair rigging, cel-shaded lighting map, expressive anime face blendshapes.',
    },
    presets: ['Shinkai Sunset Sky', 'Ufotable Demon Blade', 'Mecha Anime Pilot', 'Cherry Blossom Romance'],
  },
  {
    id: 'high_fantasy',
    name: 'High Fantasy & Mythological Lore',
    hindiName: 'हाई फैंटेसी व माइथोलॉजी',
    category: 'general',
    badge: 'Fantasy Lore',
    emoji: '🐉',
    color: '#a855f7',
    bgLight: 'bg-purple-500/10',
    borderColor: 'border-purple-500/30',
    description: 'Epic medieval castles, mythical dragons, glowing ancient magic runes, ethereal forest realms.',
    hindiDesc: 'जादुई ड्रैगन्स, मध्यकालीन महल और प्राचीन पौराणिक दुनिया।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'high fantasy concept art, intricate golden armor, glowing arcane runes, majestic dragon in background, volumetric ethereal mist, trending on ArtStation 8k',
      film: 'SCENE DIRECTION: Whispering ancient prophecy in ruined temple, magical spell glowing between fingertips, battle horn sounding over foggy mountains.',
      video: 'epic fantasy camera fly-through, dragon flight path tracking, glowing spell particles in 4k HDR, mystical cinematic lighting.',
      image_video: 'magical rune portal blend, particle spell burst composite, enchanted forest background fusion.',
      threeD: 'intricate medieval armor sculpt, cloth cape simulation, dragon wing rigging, glowing rune emissive mapping.',
    },
    presets: ['Dragon Mountain Throne', 'Elven Forest Sanctuary', 'Ancient Wizard Tower', 'Paladin Holy Light'],
  },

  // --- NON-GENERAL / MATURE / EXPLICIT / UNCENSORED GENRES ---
  {
    id: 'erotic_sensual_glamour',
    name: 'Sensual Glamour & Erotica (Mature 18+)',
    hindiName: 'कामुक व सेंसुअल ग्लैमर (18+)',
    category: 'non_general',
    badge: 'Sensual 18+',
    emoji: '💋',
    color: '#f43f5e',
    bgLight: 'bg-rose-500/15',
    borderColor: 'border-rose-500/40',
    description: 'Unrestricted intimate boudoir, sensual lingerie & silk, seductive lighting, high-fashion erotic aesthetic.',
    hindiDesc: 'कामुक सौंदर्यशास्त्र, बुडुआ फोटोग्राफी, सिल्क व कामुक प्रकाश व्यवस्था।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: true,
    promptModifiers: {
      image: 'unrestricted sensual glamour portrait, sheer silk and lace lingerie, seductive pose, soft rim lighting on curves, intimate warm bedroom atmosphere, highly detailed skin texture, 8k raw photo',
      film: 'SCENE DIRECTION: Intimate slow-burn romance, heavy breathing in low candlelight, slow caress along bare shoulder, passionate whispered dialogue, sultry jazz undertone.',
      video: 'sensual slow-motion body curves glide, intimate camera pan in candlelit ambiance, silk movement physics, ultra-high resolution skin specular highlights 60fps.',
      image_video: 'soft seductive glow transition, intimate cross-fade with heartbeat soundwave, sheer lace composite overlay.',
      threeD: 'realistic soft skin SSS shader, anatomically accurate physique sculpt, dynamic silk cloth simulation, sensual seductive pose rig.',
    },
    presets: ['Candlelit Boudoir', 'Midnight Satin Lingerie', 'Golden Hour Sensual', 'Red Velvet Seduction'],
  },
  {
    id: 'dark_gore_slasher',
    name: 'Dark Horror, Blood VFX & Slasher (Uncensored 18+)',
    hindiName: 'डार्क हॉरर, ब्लड व स्लैशर (18+)',
    category: 'non_general',
    badge: 'Blood & Gore 18+',
    emoji: '🩸',
    color: '#dc2626',
    bgLight: 'bg-red-600/15',
    borderColor: 'border-red-600/40',
    description: 'Uncensored graphic horror, realistic blood splatters, grotesque monsters, gritty psychological terror.',
    hindiDesc: 'अनसेंसर्ड हॉरर, यथार्थवादी ब्लड वीएफएक्स, खूनी थ्रिलर और खौफनाक दृश्य।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: true,
    promptModifiers: {
      image: 'raw uncensored dark horror, realistic blood splatters on cracked tiles, grotesque nightmare creature, dim flickering halogen light, hyper-detailed gore FX, gritty cinematic 8k',
      film: 'SCENE DIRECTION: Chilling heavy footsteps approaching in pitch-dark hallway, sudden blood-curdling scream, visceral blade strike, bone-chilling dread ambiance.',
      video: 'intense visceral horror sequence, fast shaky-cam slasher chase, realistic fluid blood splatter physics, eerie dark shadow tracking in 4k.',
      image_video: 'flickering darkness glitch, blood splatter alpha overlay, jump-scare flash composite, sinister heartbeat audio.',
      threeD: 'grotesque creature anatomical sculpt, fluid blood particle emitter, ripped cloth physics, dark horror specular shaders.',
    },
    presets: ['Slasher Abandoned Hospital', 'Grotesque Demon Anatomy', 'Blood Moon Cult', 'Flickering Basement Terror'],
  },
  {
    id: 'raw_uncensored_anatomy',
    name: 'Raw Unrestricted Fine Art Anatomy (18+)',
    hindiName: 'अनसेंसर्ड आर्ट एनाटॉमी व न्यूडिटी (18+)',
    category: 'non_general',
    badge: 'Raw Anatomy 18+',
    emoji: '🔞',
    color: '#fb7185',
    bgLight: 'bg-rose-600/15',
    borderColor: 'border-rose-600/40',
    description: 'Classical Michelangelo & Da Vinci anatomical mastery, unrestricted human form, muscular & skin definition.',
    hindiDesc: 'शास्त्रीय फाइन आर्ट एनाटॉमी, संपूर्ण मानवीय शरीर रचना व यथार्थवादी स्किन शेडिंग।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: true,
    promptModifiers: {
      image: 'fine art classical anatomy, unrestricted human aesthetic form, marble and golden skin tones, chiaroscuro studio lighting, precise muscular and skeletal contour, Louvre sculpture masterpiece 8k',
      film: 'SCENE DIRECTION: Classical art studio, model striking heroic anatomical pose on pedestal, sculptor chipping marble under soft skylight, contemplative silence.',
      video: '360 degree smooth anatomical turntable, dynamic lighting revealing muscle striations and skin pore realism, 4k 60fps raw studio capture.',
      image_video: 'classical marble texture morph, anatomical sketch layer dissolve, studio lighting transition.',
      threeD: 'complete anatomical mesh topology, photorealistic skin pores and subsurface scattering, dynamic muscle flex rig, full unrestricted mesh editing.',
    },
    presets: ['Michelangelo David Sculpt', 'Golden Hour Fine Art Nude', 'Athletic Anatomy Precision', 'Marble Studio Lighting'],
  },
  {
    id: 'intimate_romance',
    name: 'Intimate Romance & Passionate Cinematography (18+)',
    hindiName: 'पैशनेट रोमांस व कामुक सिनेमैटोग्राफी (18+)',
    category: 'non_general',
    badge: 'Passionate 18+',
    emoji: '🔥',
    color: '#f97316',
    bgLight: 'bg-orange-500/15',
    borderColor: 'border-orange-500/40',
    description: 'Passionate embraces, intense romantic chemistry, rain-soaked passionate encounters, steamy cinematic moods.',
    hindiDesc: 'गहन रोमांटिक केमिस्ट्री, बारिश में भीगा रोमांस और पैशनेट दृश्य।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: true,
    promptModifiers: {
      image: 'passionate romantic embrace, wet hair in torrential summer rain, intense gaze between lovers, lips inches apart, warm cinematic backlighting, high emotional intensity, 8k raw photo',
      film: 'SCENE DIRECTION: Lovers caught in thunderstorm, pulling each other close against wall, passionate breathless kiss, rain dripping down cheeks, swelling cello romance theme.',
      video: 'steamy cinematic slow-motion romance, water droplets glinting on warm skin, intimate camera rotation around lovers, 4k 60fps tender motion.',
      image_video: 'steamy glass condensation overlay, rain droplet blend, warm romantic color grade.',
      threeD: 'dual-character interactive intimacy rig, synchronized breathing blendshapes, wet skin specular maps, dynamic hair physics.',
    },
    presets: ['Torrential Rain Kiss', 'Steamy Glass Embrace', 'Sunset Beach Passion', 'Fireplace Intimacy'],
  },
  {
    id: 'cyberpunk_noir_mature',
    name: 'Edgy Cyberpunk Noir & Underground (Mature 18+)',
    hindiName: 'अंडरग्राउंड साइबरपंक नॉयर (18+)',
    category: 'non_general',
    badge: 'Underground 18+',
    emoji: '🖤',
    color: '#818cf8',
    bgLight: 'bg-indigo-500/15',
    borderColor: 'border-indigo-500/40',
    description: 'Neon-lit underground clubs, leather & latex aesthetics, cyberpunk assassins, dark sensual crime underworld.',
    hindiDesc: 'अंडरग्राउंड साइबरपंक क्लब्स, लेदर एस्थेटिक्स और डार्क अंडरवर्ल्ड रोमांस।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: true,
    promptModifiers: {
      image: 'edgy cyberpunk underground club, glossy black leather and latex outfit, glowing purple neon backlights, cigarette smoke swirling, seductive cyberpunk assassin, 8k raw',
      film: 'SCENE DIRECTION: Underground techno club pulsing with bass, assassin leaning against VIP bar, hidden blade slipping into leather sleeve, sultry dangerous dialogue.',
      video: 'pulsing neon strobe light tracking, sleek leather reflection movement, slow motion smoke swirl, dark techno beat-sync 4k.',
      image_video: 'neon smoke overlay, techno strobe glitch transition, glossy leather sheen blend.',
      threeD: 'glossy latex and leather PBR materials, high-poly cybernetic corset, dark neon lighting setup, assassin stance pose rig.',
    },
    presets: ['Underground Neon VIP', 'Leather Cyberpunk Assassin', 'Smoke & Strobe Noir', 'Chrome Spine Seduction'],
  },
  {
    id: 'gothic_dark_fantasy',
    name: 'Gothic Dark Fantasy & Vampire Seduction (18+)',
    hindiName: 'गॉथिक वैम्पायर व डार्क फैंटेसी (18+)',
    category: 'non_general',
    badge: 'Gothic 18+',
    emoji: '🦇',
    color: '#a855f7',
    bgLight: 'bg-purple-600/15',
    borderColor: 'border-purple-600/40',
    description: 'Victorian vampire castles, gothic velvet corsets, seductive blood pacts, dark sensual immortality.',
    hindiDesc: 'गॉथिक महल, वैम्पायर रोमांस, वेलवेट कोर्सेट और डार्क फंतासी।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: true,
    promptModifiers: {
      image: 'gothic dark fantasy vampire queen, ornate black velvet and lace gown, ruby red wine glass, pale skin with crimson lips, opulent moonlit gothic cathedral, 8k hyper-detail',
      film: 'SCENE DIRECTION: Moonlit stone balcony over misty forest, vampire countess leaning toward mortal neck, fangs subtly glinting, whispered hypnotic promise of immortality.',
      video: 'dramatic gothic cape flow, bat swarm morph transition, candle flame flickering in vampire gaze, 4k cinematic elegance.',
      image_video: 'moonlit fog composite, gothic stained glass window fusion, blood-red vignette overlay.',
      threeD: 'victorian gothic dress cloth simulation, pale porcelain skin shader, ornate gothic cathedral environment asset.',
    },
    presets: ['Vampire Moonlit Balcony', 'Gothic Cathedral Seduction', 'Velvet & Blood Chalice', 'Misty Crypt Immortal'],
  },
  {
    id: 'brutal_combat_action',
    name: 'Brutal Unrestricted Combat & Martial Arts (18+)',
    hindiName: 'क्रूर कॉम्बैट व मार्शल आर्ट्स (18+)',
    category: 'non_general',
    badge: 'Brutal Combat 18+',
    emoji: '⚔️',
    color: '#eab308',
    bgLight: 'bg-yellow-500/15',
    borderColor: 'border-yellow-500/40',
    description: 'High-impact brutal fight scenes, John Wick style gun-fu, raw bone-crunching martial arts choreography.',
    hindiDesc: 'हाई-इम्पैक्ट फाइट सीन्स, जॉन विक स्टाइल गन-फू और क्रूर कॉम्बैट कोरियोग्राफी।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: true,
    promptModifiers: {
      image: 'raw intense action combat, martial artist mid-air roundhouse kick, sweat and blood spray captured in ultra-high shutter speed, gritty neon alley backdrop, 8k action photography',
      film: 'SCENE DIRECTION: Close-quarters combat in neon rain, bone-shattering parry into spinning elbow strike, kinetic camera following every impact, heart-pounding drum rhythm.',
      video: '60fps dynamic fight choreography, kinetic camera whip-pan on impact, slow-motion hit-stop physics, debris and blood particle tracking.',
      image_video: 'motion blur speed impact streaks, muzzle flash particle composite, action camera shake FX.',
      threeD: 'advanced martial arts skeletal rig, ragdoll impact physics, sweat particle emitters, dynamic combat motion capture sequence.',
    },
    presets: ['Neon Alley Gun-Fu', 'Rain-Soaked Martial Combat', 'Dojo Master Duel', 'Tactical Strike Strike'],
  },
  {
    id: 'world_cinema_global',
    name: 'Global World Cinema & Cross-Cultural Epics (All Over World)',
    hindiName: 'ऑल ओवर वर्ल्ड सिनेमा व ग्लोबल कल्चर',
    category: 'all_over_world',
    badge: '🌍 All Over World',
    emoji: '🌍',
    color: '#10b981',
    bgLight: 'bg-emerald-500/10',
    borderColor: 'border-emerald-500/30',
    description: 'Cinematic masterpieces spanning African Amapiano, Latin Reggaeton, Middle Eastern Maqam, Celtic Highlands, and Tokyo Cyber.',
    hindiDesc: 'ऑल ओवर वर्ल्ड सिनेमा, अफ्रीका, लैटिन अमेरिका, मध्य पूर्व और सेल्टिक संस्कृतियाँ।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'global world cinema aesthetic, cross-cultural masterpiece, vibrant regional cinematography, authentic traditional attire, cinematic global grading 8k',
      film: 'SCENE DIRECTION: Rich cultural storytelling, sweeping landscape tracking shot transitioning between global cultural heritage and modern cinematic rhythm.',
      video: '4k global cinematic journey, fluid cultural camera choreography, authentic regional lighting and atmosphere grading.',
      image_video: 'seamless global cross-fade transition, cultural motif overlay blending, rich international aesthetic.',
      threeD: 'authentic regional architecture PBR shaders, traditional cultural artifact modeling, global environment lighting.',
    },
    presets: ['Global Cultural Epic', 'International Festival Scene', 'Cross-Border Adventure', 'World Harmony Showcase'],
  },
  {
    id: 'african_afrobeat_amapiano',
    name: 'African Amapiano & Lagos Afrobeat Groove',
    hindiName: 'अमापियानो लाग-ड्रम व अफ्रीकी ग्रूव',
    category: 'all_over_world',
    badge: '🥁 Africa & Amapiano',
    emoji: '🥁',
    color: '#f97316',
    bgLight: 'bg-orange-500/10',
    borderColor: 'border-orange-500/30',
    description: 'Soulful South African log-drum bass drops, vibrant Lagos street culture, shakers, and vibrant dance choreography.',
    hindiDesc: 'अमापियानो लाग-ड्रम बास, लागोस स्ट्रीट कल्चर और अफ्रीकी डांस ग्रूव।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'vibrant Lagos street dance culture, South African Amapiano log-drum energy, warm golden hour sun, joyful expressive portraits, colorful dashiki fashion, 8k photography',
      film: 'SCENE DIRECTION: Energetic street dance circle in Lagos, pulsating log-drum bass rhythm, golden sunset glow, vibrant community celebration.',
      video: '60fps dynamic Afrobeat dance choreography tracking, rhythmic camera bounce sync, vibrant festival color grade.',
      image_video: 'sun-drenched rhythm transition, vibrant cultural pattern overlay, warm energetic grade.',
      threeD: 'expressive character skin shaders, dynamic dashiki cloth simulation, energetic street party environment mesh.',
    },
    presets: ['Lagos Street Vibe', 'South African Log-Drum Drop', 'African Sunset Festival', 'Golden Tribal Rhythm'],
  },
  {
    id: 'latin_caribbean_dembow',
    name: 'Latin Reggaeton & Caribbean Dembow',
    hindiName: 'लैटिन रेगेटन व कैरेबियन डेमबो',
    category: 'all_over_world',
    badge: '🌴 Latin & Caribbean',
    emoji: '🌴',
    color: '#f43f5e',
    bgLight: 'bg-rose-500/10',
    borderColor: 'border-rose-500/30',
    description: 'Energetic Puerto Rican & Colombian Latin urban groove featuring Dembow beats, Spanish flamenco guitars, and carnival sunset colors.',
    hindiDesc: 'प्यूर्टो रिकन व कोलंबियन लैटिन अर्बन ग्रूव, डेमबो बीट और स्पेनिश गिटार।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'energetic Puerto Rican Caribbean carnival, neon coastal sunset, Spanish flamenco guitars, dancers in vibrant tropical attire, cinematic 8k',
      film: 'SCENE DIRECTION: Beachside Caribbean party at dusk, infectious dembow rhythm, dancers swaying under string lights, warm tropical breeze.',
      video: 'dynamic Latin dance camera movement, ocean waves coastal tracking, vibrant HDR color grading 60fps.',
      image_video: 'coastal sunset light transition, tropical palm leaf shadow composite, warm golden pulse.',
      threeD: 'tropical coastal environment PBR, vibrant carnival costume cloth simulation, warm sunset illumination.',
    },
    presets: ['Puerto Rican Carnival', 'Spanish Nylon Sunset', 'Medellin Urban Vibe', 'Havana Seaside Jazz'],
  },
  {
    id: 'middle_eastern_arabic',
    name: 'Middle Eastern Desert Oud & Maqam Epic',
    hindiName: 'मध्य पूर्व अरबी ऊद व मक़ाम',
    category: 'all_over_world',
    badge: '🕌 Middle East',
    emoji: '🕌',
    color: '#d97706',
    bgLight: 'bg-amber-500/10',
    borderColor: 'border-amber-500/30',
    description: 'Enchanting Arabian desert landscape melodies, traditional Maqam scales, resonant Oud strings, and Darbuka percussion.',
    hindiDesc: 'अरबी रेगिस्तान, मक़ाम स्केल, गूंजते हुए ऊद और दरबारुका पर्केशन।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'enchanting Arabian desert oasis at twilight, ornate palace architecture, traditional Oud player in silhouette, golden sand dunes, cinematic 8k',
      film: 'SCENE DIRECTION: Desert caravan under starry night sky, melancholic Oud string solo echoing across sand dunes, flickering campfire warmth.',
      video: 'smooth cinematic drone sweep over desert dunes, candlelit tent interior tracking, warm amber cinematic grade.',
      image_video: 'starlit desert night transition, warm campfire glow composite, mystical Arabian ambiance.',
      threeD: 'intricate Islamic geometric tile shaders, sand dune displacement mapping, Oud string instrument 3D model.',
    },
    presets: ['Arabian Desert Caravan', 'Oud Maqam Soliloquy', 'Royal Palace Oasis', 'Darbuka Rhythmic Fire'],
  },
  {
    id: 'celtic_irish_folk',
    name: 'Celtic Highland Fiddle & Irish Folk',
    hindiName: 'सेल्टिक आयरिश हाइलैंड लोकधुन',
    category: 'all_over_world',
    badge: '🍀 Celtic & Irish',
    emoji: '🍀',
    color: '#059669',
    bgLight: 'bg-emerald-600/10',
    borderColor: 'border-emerald-600/30',
    description: 'Spirited Gaelic melodies with fast Irish tin whistle runs, rhythmic Bodhrán drum beats, and emerald green mists.',
    hindiDesc: 'गेलिक धुनें, आयरिश टिन व्हिसल, बोध्रान ड्रम और हरे-भरे हाइलैंड्स।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'misty emerald Scottish Highlands castle, Irish folk musicians playing fiddle and tin whistle by fireplace, warm tavern atmosphere, 8k render',
      film: 'SCENE DIRECTION: Misty green cliffside overlooking roaring Atlantic ocean, spirited violin jig echoing through ancient stone tavern.',
      video: 'cinematic drone flyover of emerald hills, cozy hearth fire camera track, organic Celtic lighting grade.',
      image_video: 'misty Highland fog transition, warm hearth glow composite, Celtic knot motif overlay.',
      threeD: 'ancient stone castle PBR textures, tartan plaid cloth simulation, violin and harp musical instrument models.',
    },
    presets: ['Emerald Highland Mist', 'Irish Pub Jig Celebration', 'Celtic Harp Sanctuary', 'Bodhrán War Drum'],
  },
  {
    id: 'bollywood_masala_epic',
    name: 'Bollywood Masala & Grand Romantic Blockbuster',
    hindiName: 'बॉलीवुड मसाला व भव्य रोमांटिक ब्लॉकबस्टर',
    category: 'indian_bollywood',
    badge: '🎬 Bollywood Masala',
    emoji: '🎬',
    color: '#ec4899',
    bgLight: 'bg-pink-500/10',
    borderColor: 'border-pink-500/30',
    description: 'Grand cinematic romance, rain-soaked Swiss Alps dance sequences, vibrant Sangeet celebrations, and iconic playback melodies.',
    hindiDesc: 'भव्य बॉलीवुड रोमांस, बारिश में डांस सीक्वेंस, संगीत समारोह और सदाबहार गाने।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'iconic Bollywood romantic blockbuster scene, vibrant silk lehenga and designer sherwani, snow-capped Swiss Alps background with rain spray, cinematic 8k lighting, anamorphic lens flare',
      film: 'SCENE DIRECTION: Sweeping crane shot of grand Bollywood dance sequence, lead couple dancing in pouring rain surrounded by background dancers, vibrant technicolor palette.',
      video: 'high-energy 60fps Bollywood choreography tracking shot, dynamic costume flow, lush cinematic color grading.',
      image_video: 'magical rain-drop transition, vibrant color saturation burst, romantic cinematic haze overlay.',
      threeD: 'luxurious Bollywood palace set PBR shaders, detailed silk costume simulation, dramatic stage spotlighting.',
    },
    presets: ['Swiss Alps Rain Romance', 'Royal Sangeet Celebration', 'Hero Entry slow-motion', 'Iconic Melody Duet'],
  },
  {
    id: 'south_indian_mass_action',
    name: 'South Indian Mass Action & Tollywood Epic',
    hindiName: 'साउथ इंडियन मास एक्शन व टॉलिवुड हीरो एपिक',
    category: 'indian_bollywood',
    badge: '🔥 Tollywood & Mass Action',
    emoji: '🔥',
    color: '#eab308',
    bgLight: 'bg-yellow-500/10',
    borderColor: 'border-yellow-500/30',
    description: 'High-octane slow-motion hero entry, gravity-defying action stunts, whistle-worthy punch dialogues, and heavy brass percussion beats.',
    hindiDesc: 'मास हीरो एंट्री, स्लो-मोशन एक्शन स्टंट, दमदार पंच डायलॉग और भारी ब्रास बीट्स।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'explosive South Indian Tollywood mass action hero entry, slow motion flying dust and debris, intense heroic glare, massive temple backdrop, cinematic 8k',
      film: 'SCENE DIRECTION: Dramatic low-angle tracking shot of mass hero stepping out of firestorm, flying cars, powerful brass drum beat drop.',
      video: 'high-speed 120fps slow-motion action impact, dynamic particle debris simulation, high-contrast cinematic grade.',
      image_video: 'fiery explosion transition, dynamic shutter-speed motion blur, epic cinematic title card reveal.',
      threeD: 'detailed action hero 3D rig, flying debris particle systems, ruined ancient temple environment mesh.',
    },
    presets: ['Mass Hero Fire Entry', 'Temple Courtyard Brawl', 'Whistle-Worthy Slow-Mo', 'High-Octane Chase'],
  },
  {
    id: 'bombay_noir_underworld',
    name: 'Bombay Noir & Rain-Slicked Underworld Thriller',
    hindiName: 'बॉम्बे नॉइर व रेन-स्लिकेड अंडरवर्ल्ड थ्रिलर',
    category: 'indian_bollywood',
    badge: '🕶️ Bombay Noir',
    emoji: '🕶️',
    color: '#6366f1',
    bgLight: 'bg-indigo-500/10',
    borderColor: 'border-indigo-500/30',
    description: 'Gritty Mumbai rain-slicked alleyways, underworld dons in sunglasses, neon chawl lights, and suspenseful tabla-beat basslines.',
    hindiDesc: 'ग्रेटी मुंबई की बारिश वाली गलियाँ, अंडरवर्ल्ड डॉन, नियोन चॉल और सस्पेंसफुल तबला बीट्स।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'gritty Bombay noir underworld thriller, rain-slicked Mumbai street at midnight, vintage Ambassador car, neon tea stall sign, moody cinematic lighting 8k',
      film: 'SCENE DIRECTION: Suspenseful stakeout in narrow Mumbai chawl alleyway, flickering fluorescent bulb overhead, shadow play and heavy rain ambiance.',
      video: 'moody handheld camera tracking through neon-lit Mumbai rainy nights, cinematic teal-and-orange grade.',
      image_video: 'rain-splattered lens transition, neon reflection shimmer, suspenseful noir fade.',
      threeD: 'urban Mumbai chawl architecture PBR textures, volumetric rain and puddle shader, retro car modeling.',
    },
    presets: ['Midnight Chawl Stakeout', 'Rain-Slicked Marine Drive', 'Underworld Don Den', 'Retro Bombay Chase'],
  },
  {
    id: 'indian_classical_sufi',
    name: 'Indian Classical Sitar & Sufi Mystic Qawwali',
    hindiName: 'भारतीय शास्त्रीय सितार व सूफी कव्वाली',
    category: 'indian_bollywood',
    badge: '🎼 Sufi & Classical',
    emoji: '🎼',
    color: '#14b8a6',
    bgLight: 'bg-teal-500/10',
    borderColor: 'border-teal-500/30',
    description: 'Soulful Sufi shrine shrines, transcendental Sitar and Bansuri melodies, rhythmic Tabla and Harmonium spiritual trance.',
    hindiDesc: 'सूफी दरगाह, सितार और बांसुरी की जादुई धुनें, तबला और हारमोनियम का रूहानी संगीत।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'mystical Sufi shrine courtyard at twilight, Qawwali singers in white kurta and taqiyah, flickering oil lamps (diyas), intricate marble arches, cinematic 8k',
      film: 'SCENE DIRECTION: Intimate close-up of master Sitar player’s fingers bending strings, reverberating tabla and harmonium notes in ancient illuminated courtyard.',
      video: 'smooth spiritual camera movement over glowing oil lamps, hypnotic rhythm sync, warm golden hour Sufi color grade.',
      image_video: 'twilight diya flame transition, spiritual dust particle bokeh, golden aura composite.',
      threeD: 'intricate Mughal marble jali architecture shaders, traditional sitar and tabla musical instruments, volumetric candle lighting.',
    },
    presets: ['Sufi Shrine Twilight', 'Classical Sitar Soliloquy', 'Harmonium & Tabla Jam', 'Mughal Courtyard Echo'],
  },
  {
    id: 'punjabi_bhangra_dhol',
    name: 'Punjabi Bhangra & Dhol Dhamaka Beats',
    hindiName: 'पंजाबी भांगड़ा व ढोल धमाकेदार बीट्स',
    category: 'indian_bollywood',
    badge: '🌾 Punjabi Bhangra',
    emoji: '🌾',
    color: '#f97316',
    bgLight: 'bg-orange-500/10',
    borderColor: 'border-orange-500/30',
    description: 'High-energy Punjabi dhol drum beats, vibrant mustard fields, enthusiastic folk dancers, and colorful turbans.',
    hindiDesc: 'ऊर्जावान पंजाबी ढोल बीट्स, पीले सरसों के खेत, भांगड़ा और रंग-बिरंगी पगड़ियाँ।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'vibrant Punjabi Bhangra harvest celebration, golden mustard fields (sarson ke khet), energetic dancers in colorful turbans and kurta, beating traditional dhol drums, 8k render',
      film: 'SCENE DIRECTION: High-energy Bhangra circle dance in Punjab village courtyard, powerful dhol rhythm drop, dust kicking up in golden sunlight.',
      video: 'fast-paced 60fps dynamic camera orbit around energetic Bhangra dancers, saturated festive color grading.',
      image_video: 'sun-drenched golden field transition, mustard flower petal particle burst, vibrant festive pulse.',
      threeD: 'traditional Punjabi attire cloth simulation, mustard field volumetric grass shaders, dhol drum instrument 3D model.',
    },
    presets: ['Golden Mustard Field Dance', 'Village Dhol Dhamaka', 'Bhangra Night Celebration', 'Punjabi Wedding Fest'],
  },
  {
    id: 'k_pop_j_rock_east_asian',
    name: 'East Asian K-Pop, J-Rock & Neo-Tokyo Cyber',
    hindiName: 'कोरियाई के-पॉप, जापानी जे-रॉक व साइको-टोक्यो',
    category: 'all_over_world',
    badge: '🌸 K-Pop & J-Rock',
    emoji: '🌸',
    color: '#ec4899',
    bgLight: 'bg-pink-500/10',
    borderColor: 'border-pink-500/30',
    description: 'Neon-soaked Seoul stage choreography, high-octane Japanese anime J-Rock guitar riffs, and futuristic Neo-Tokyo aesthetics.',
    hindiDesc: 'नियोन सराबोर सियोल स्टेज कोरियोग्राफी, जापानी जे-रॉक गिटार रिफ़्स और भविष्यवादी टोक्यो।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'futuristic Seoul K-pop concert stage, neon laser lights, stylish streetwear fashion, holographic projections, cinematic 8k render',
      film: 'SCENE DIRECTION: High-energy K-pop dance break with synchronized laser choreography in high-tech Shibuya neon intersection.',
      video: '60fps dynamic camera sweep around neon stage, rhythmic pulse, vibrant cyber-punk color grade.',
      image_video: 'neon glow pulse transition, holographic particle overlay, cyberpunk neon gradient.',
      threeD: 'cyberpunk street environment PBR shaders, futuristic fashion clothing simulation, neon holographic shader effects.',
    },
    presets: ['Seoul Neon Stage', 'Shibuya J-Rock Riot', 'Holographic Cyber Dance', 'K-Pop MV Cinematic'],
  },
  {
    id: 'latin_mariachi_samba',
    name: 'Mexican Mariachi, Tango & Brazilian Samba',
    hindiName: 'मेक्सिकन मारियाची, अर्जेंटीना टैंगो व ब्राजीलियाई साम्बा',
    category: 'all_over_world',
    badge: '💃 Latin Grooves',
    emoji: '💃',
    color: '#f59e0b',
    bgLight: 'bg-amber-500/10',
    borderColor: 'border-amber-500/30',
    description: 'Passionate Argentine Tango accordions, festive Mexican Mariachi trumpets, and vibrant Rio Carnival Samba drums.',
    hindiDesc: 'अर्जेंटीना टैंगो, मेक्सिकन मारियाची ट्रंपेट और रियो कार्निवल साम्बा ड्रम्स।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'vibrant Rio de Janeiro carnival celebration, feathered samba dancers, golden sunset beach, energetic brass band, 8k photography',
      film: 'SCENE DIRECTION: Passionate Buenos Aires rooftop tango dance under warm streetlamps, romantic accordion melody echoing through cobblestone alley.',
      video: 'dynamic Latin dance footwork tracking shot, warm golden hour lighting, vibrant carnival HDR grade.',
      image_video: 'sunset golden hour transition, festive confetti particle overlay, warm Latin pulse.',
      threeD: 'feathered carnival costume simulation, cobblestone street PBR textures, brass musical instrument models.',
    },
    presets: ['Rio Carnival Samba', 'Buenos Aires Rooftop Tango', 'Mariachi Fiesta Sunset', 'Havana Street Rumba'],
  },
  {
    id: 'european_opera_waltz',
    name: 'European Classical Opera & Viennese Waltz',
    hindiName: 'यूरोपीय ओपेरा, फ्रेंच चान्सन व वियनीज वाल्ट्ज',
    category: 'all_over_world',
    badge: '🎻 European Opera & Waltz',
    emoji: '🎻',
    color: '#8b5cf6',
    bgLight: 'bg-purple-500/10',
    borderColor: 'border-purple-500/30',
    description: 'Grand Viennese ballroom crystal chandeliers, passionate Italian opera vocals, and romantic French accordion cafes.',
    hindiDesc: 'वियना का भव्य बॉलरूम, इटालियन ओपेरा स्वर और फ्रेंच कैफे संगीत।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'grand Viennese ballroom, crystal chandeliers reflecting golden light, aristocratic couples waltzing in elegant evening gowns, 8k render',
      film: 'SCENE DIRECTION: Sweep of camera across majestic Paris opera house stage during soaring soprano aria, rich velvet curtains and candlelight.',
      video: 'smooth aristocratic ballroom glide tracking shot, warm amber chandelier lighting grade.',
      image_video: 'chandelier crystal sparkle transition, golden romantic glow composite, classical art aesthetic.',
      threeD: 'baroque architecture PBR shaders, silk and velvet ball gown simulations, ornate crystal chandelier modeling.',
    },
    presets: ['Viennese Crystal Waltz', 'Parisian Opera Aria', 'French Accordion Cafe', 'Royal Palace Ball'],
  },
  {
    id: 'nordic_viking_folk',
    name: 'Nordic Ambient, Old Norse Taglharpa & Viking Folk',
    hindiName: 'नॉर्डिक एम्बिएंट व वाइकिंग लोक संगीत',
    category: 'all_over_world',
    badge: '🪓 Nordic & Viking',
    emoji: '🪓',
    color: '#06b6d4',
    bgLight: 'bg-cyan-500/10',
    borderColor: 'border-cyan-500/30',
    description: 'Deep resonant Taglharpa drones, misty Norwegian fjords, ancient Runic chants, and epic Norse saga atmospheres.',
    hindiDesc: 'नॉर्डिक फोजॉर्ड, प्राचीन रुनिक मंत्र, टैग्लहार्पा गूंज और वाइकिंग गाथाएँ।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'misty Norwegian fjord at dawn, Viking longship moored by rocky shore, warrior playing ancient taglharpa instrument by campfire, 8k cinematic',
      film: 'SCENE DIRECTION: Drone flight over snow-capped Scandinavian mountains, deep chanting ritual around sacred stone circle in twilight.',
      video: 'slow cinematic drone sweep over icy northern waters, moody Nordic blue-gray color grading.',
      image_video: 'glacial mist fog transition, cold blue cinematic atmosphere, runic stone symbol reveal.',
      threeD: 'rocky fjord landscape PBR shaders, weathered wooden longship model, fur and leather Viking costume simulation.',
    },
    presets: ['Fjord Longship Dawn', 'Taglharpa Rune Chant', 'Nordic Winter Forest', 'Valhalla Feast Hall'],
  },
  {
    id: 'caribbean_reggae_dub',
    name: 'Jamaican Reggae, Dub Basslines & Dancehall',
    hindiName: 'जमैकन रेगे, डब बासलाइन व डांसहॉल',
    category: 'all_over_world',
    badge: '🇯🇲 Reggae & Dub',
    emoji: '🇯🇲',
    color: '#10b981',
    bgLight: 'bg-emerald-500/10',
    borderColor: 'border-emerald-500/30',
    description: 'Relaxed Kingston island grooves, deep sub-bass dub echoes, vibrant Rastafarian colors, and sunny Caribbean beaches.',
    hindiDesc: 'किंग्स्टन द्वीप ग्रूव, डब बास गूंज, रास्तफारी रंग और धूप वाले कैरेबियन समुद्र तट।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'sunny Kingston Jamaica beach shack party, Rastafarian red gold and green colors, vinyl turntable sound system, palm trees, cinematic 8k',
      film: 'SCENE DIRECTION: Relaxed evening beach bonfire jam session, infectious off-beat guitar skank and deep sub-bass pulse.',
      video: 'warm golden sun lens flare tracking shot, relaxed island rhythm, saturated tropical color grading.',
      image_video: 'tropical wave motion transition, sun-drenched palm shadow overlay, vibrant island vibe.',
      threeD: 'tropical beach environment PBR shaders, sound system speaker stacks, vintage island shack modeling.',
    },
    presets: ['Kingston Beach SoundSystem', 'Dub Bass Echo Sunset', 'Rasta Roots Jam', 'Island Breeze Groove'],
  },
  {
    id: 'mediterranean_bouzouki',
    name: 'Mediterranean Greek Bouzouki & Levantine Tarab',
    hindiName: 'ग्रीक बुज़ुकी व भूमध्यसागरीय लोक संगीत',
    category: 'all_over_world',
    badge: '🏛️ Mediterranean Folk',
    emoji: '🏛️',
    color: '#3b82f6',
    bgLight: 'bg-blue-500/10',
    borderColor: 'border-blue-500/30',
    description: 'Azure Santorini sea views, lively Greek bouzouki fingerpicking, and soulful Levantine tarab melodies.',
    hindiDesc: 'सैंटोरिनी के नीले समुद्र, ग्रीक बुज़ुकी और भूमध्यसागरीय लोक धुनें।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'picturesque Santorini whitewashed cliffside village at sunset, blue domed church, musician playing bouzouki on tavern terrace, 8k render',
      film: 'SCENE DIRECTION: Golden hour pan across sparkling Aegean sea, joyous Greek tavern plate-smashing celebration and fast bouzouki melody.',
      video: 'smooth Aegean coastal drone flight, warm Mediterranean sun filtering through bougainvillea flowers.',
      image_video: 'azure sea wave shimmer transition, sunlit whitewashed wall composite, Greek island warmth.',
      threeD: 'whitewashed Mediterranean architecture PBR shaders, bougainvillea flower particle meshes, bouzouki instrument model.',
    },
    presets: ['Santorini Sunset Tavern', 'Greek Bouzouki Celebration', 'Aegean Coastal Breeze', 'Levantine Tarab Night'],
  },
  {
    id: 'tollywood_telugu_epic',
    name: 'Tollywood & Telugu Cinema (Hyderabad Epic)',
    hindiName: 'टॉलिवुड व तेलुगु सिनेमा (हैदराबाद एपिक)',
    category: 'indian_bollywood',
    badge: '👑 Tollywood (Telugu)',
    emoji: '👑',
    color: '#f59e0b',
    bgLight: 'bg-amber-500/10',
    borderColor: 'border-amber-500/30',
    description: 'Grand Baahubali scale visual effects, thunderous action choreography, whistle-worthy hero elevations, and rich classical Telugu melodies.',
    hindiDesc: 'बाहुबली स्केल वीएफएक्स, भव्य एक्शन, मास हीरो एलिवेशन और समृद्ध तेलुगु धुनें।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'grand Tollywood epic film scene, massive ancient kingdom palace, heroic warrior posture in golden armor, roaring waterfall background, cinematic 8k',
      film: 'SCENE DIRECTION: High-octane slow-motion hero elevation shot in Hyderabad film city, dramatic wind blowing through hair, thumping war drums beat drop.',
      video: '120fps high-speed action impact tracking shot, epic mythological scale lighting, cinematic gold-and-bronze grading.',
      image_video: 'golden waterfall spray transition, epic title reveal, mythological scale composite.',
      threeD: 'ancient kingdom architecture PBR shaders, golden warrior armor simulation, massive waterfall particle systems.',
    },
    presets: ['Baahubali Royal Court', 'Mass Hero Elevation', 'Waterfall War Clash', 'Telangana Folk Melody'],
  },
  {
    id: 'kollywood_tamil_action',
    name: 'Kollywood & Tamil Cinema (Chennai Gaana & Action)',
    hindiName: 'कोलिवुड व तमिल सिनेमा (चेन्नई गाना व एक्शन)',
    category: 'indian_bollywood',
    badge: '⚡ Kollywood (Tamil)',
    emoji: '⚡',
    color: '#ef4444',
    bgLight: 'bg-red-500/10',
    borderColor: 'border-red-500/30',
    description: 'Electrifying Chennai Gaana beats, stylish thug-life action sequences, vibrant street festival dance, and soulful Ilaiyaraaja/AR Rahman melodies.',
    hindiDesc: 'चेन्नई गाना बीट्स, स्टाइलिश एक्शन, स्ट्रीट फेस्टिवल डांस और सुरीली तमिल धुनें।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'stylish Kollywood action sequence in Chennai harbor at sunset, sunglasses and leather jacket hero, gritty texture, cinematic 8k',
      film: 'SCENE DIRECTION: Energetic street festival Gaana dance celebration in Madurai temple street, colorful powder throwing, rapid drum beat sync.',
      video: 'dynamic handheld action camera tracking, high-contrast neon and sunset color grade, 60fps.',
      image_video: 'temple festival color burst transition, rhythmic motion blur, vibrant South Indian atmosphere.',
      threeD: 'Chennai street market PBR shaders, dynamic dust and smoke simulation, vintage truck models.',
    },
    presets: ['Madurai Temple Festival', 'Thug Life Harbor Action', 'Chennai Gaana Dance', 'Soulful Melody Romance'],
  },
  {
    id: 'mollywood_kerala_thriller',
    name: 'Mollywood & Malayalam Cinema (Kerala Thriller & Drama)',
    hindiName: 'मोलिवुड व मलयालम सिनेमा (केरल थ्रिलर व नाटक)',
    category: 'indian_bollywood',
    badge: '🌴 Mollywood (Malayalam)',
    emoji: '🌴',
    color: '#10b981',
    bgLight: 'bg-emerald-500/10',
    borderColor: 'border-emerald-500/30',
    description: 'Gritty realist storytelling, lush green Kerala backwaters, atmospheric psychological suspense, and soulful classical Carnatic flute notes.',
    hindiDesc: 'यथार्थवादी कहानी, केरल की हरी-भरी वादियाँ, सस्पेंस थ्रिलर और कार्नेटिक बांसुरी संगीत।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'serene Kerala backwater houseboat at dawn, misty palm trees, realistic cinematic framing, moody atmospheric thriller lighting, 8k',
      film: 'SCENE DIRECTION: Slow brooding tracking shot through rain-drenched rubber plantation in Kerala, subtle ambient synth and haunting bamboo flute score.',
      video: 'moody cinematic slow-pan across misty backwaters, organic natural color grading.',
      image_video: 'misty morning river fog transition, peaceful green palette, subtle ripple composite.',
      threeD: 'Kerala houseboat and backwater environment PBR, lush palm tree foliage shaders, realistic water ripple simulation.',
    },
    presets: ['Backwater Houseboat Dawn', 'Rain-Drenched Rubber Estate', 'Psychological Suspense', 'Carnatic Flute Melody'],
  },
  {
    id: 'sandalwood_kannada_kgf',
    name: 'Sandalwood & Kannada Cinema (KGF Gold Mine Grit)',
    hindiName: 'सैंडलवुड व कन्नडा सिनेमा (केजीएफ गोल्ड माइन ग्रिट)',
    category: 'indian_bollywood',
    badge: '⛏️ Sandalwood (Kannada)',
    emoji: '⛏️',
    color: '#84cc16',
    bgLight: 'bg-lime-500/10',
    borderColor: 'border-lime-500/30',
    description: 'Gritty KGF gold mine industrial action, heavy metal guitar riffs, smoky underground rebellion, and rugged hero charisma.',
    hindiDesc: 'केजीएफ गोल्ड माइन खदान एक्शन, भारी मेटल गिटार, और रफ-टफ हीरो अंदाज।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'dark industrial gold mine setting, smoky atmosphere, rugged action hero with vintage machine gun, fiery sparks, cinematic 8k',
      film: 'SCENE DIRECTION: Slow motion walk of fearless hero through smoke-filled underground gold mine, heavy industrial percussion beat drop.',
      video: 'high-contrast gritty dark action grading, sparks flying 120fps slow motion, industrial aesthetic.',
      image_video: 'fiery spark shower transition, smoky industrial haze overlay, dark cinematic punch.',
      threeD: 'underground mine tunnel PBR shaders, volumetric smoke and spark particle simulation, industrial machinery 3D models.',
    },
    presets: ['KGF Underground Rebellion', 'Gold Mine Industrial Action', 'Rugged Hero Walk', 'Mysore Palace Heritage'],
  },
  {
    id: 'pollywood_punjabi_cinema',
    name: 'Pollywood & Punjabi Cinema (Chandigarh Comedy & Folk)',
    hindiName: 'पॉलीवुड व पंजाबी सिनेमा (चंडीगढ़ कॉमेडी व लोककथा)',
    category: 'indian_bollywood',
    badge: '🚜 Pollywood (Punjabi)',
    emoji: '🚜',
    color: '#f97316',
    bgLight: 'bg-orange-500/10',
    borderColor: 'border-orange-500/30',
    description: 'Vibrant Punjabi village life, tractor rallies, energetic bhangra weddings, hearty laughter, and romantic folk ballads.',
    hindiDesc: 'पंजाबी गाँव का जीवन, ट्रैक्टर रैली, भांगड़ा शादियाँ और रोमांटिक लोक गीत।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'joyful Punjabi village wedding celebration, tractor with colorful floral decor, cheerful actors in traditional Phulkari and kurta, sunny 8k',
      film: 'SCENE DIRECTION: High-energy village courtyard dance with dhol beats, laughter and romantic banter under Banyan tree.',
      video: 'sun-drenched upbeat camera movement, saturated festive Punjabi color grading, 60fps.',
      image_video: 'golden wheat field sunshine transition, vibrant color saturation, joyful village festival vibe.',
      threeD: 'punjabi village farm PBR environment, tractor 3D model, traditional Phulkari embroidery cloth simulation.',
    },
    presets: ['Village Wedding Fest', 'Tractor Ride Romance', 'Bhangra Dhol Beats', 'Chandigarh Vibe Comedy'],
  },
  {
    id: 'bhojpuri_purvanchal_beats',
    name: 'Bhojpuri Cinema & Purvanchal Folk Beats',
    hindiName: 'भोजपुरी सिनेमा व पूर्वांचल लोक बीट्स',
    category: 'indian_bollywood',
    badge: '🎤 Bhojpuri & Purvanchal',
    emoji: '🎤',
    color: '#d946ef',
    bgLight: 'bg-fuchsia-500/10',
    borderColor: 'border-fuchsia-500/30',
    description: 'High-energy Bhojpuri folk item numbers, vibrant Chhath Puja riverbank devotion, dholak rhythms, and celebratory village beats.',
    hindiDesc: 'भोजपुरी लोक गीत, छठ पूजा घाट, ढोलक की थाप और धमाकेदार जश्न।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'vibrant Bhojpuri village stage show celebration, colorful stage lighting, energetic dancers in bright traditional attire, festive 8k',
      film: 'SCENE DIRECTION: Energetic village marriage procession with exuberant dancing, dholak and trumpets playing high-octane folk rhythm.',
      video: 'fast-paced vibrant stage performance camera orbit, saturated festive color grading.',
      image_video: 'stage spotlight color transition, celebratory confetti burst, high-energy folk pulse.',
      threeD: 'village festival stage PBR shaders, traditional folk costume simulation, celebratory lighting fixtures.',
    },
    presets: ['Chhath Puja Ghat River', 'Village Stage Dance', 'Dholak Folk Celebration', 'Purvanchal Celebration'],
  },
  {
    id: 'marathi_cinema_lavani',
    name: 'Marathi Cinema & Lavani Folk Drama',
    hindiName: 'मराठी सिनेमा व लावणी लोक नाटक',
    category: 'indian_bollywood',
    badge: '🎭 Marathi & Lavani',
    emoji: '🎭',
    color: '#06b6d4',
    bgLight: 'bg-cyan-500/10',
    borderColor: 'border-cyan-500/30',
    description: 'Artistic Marathi parallel cinema storytelling, energetic Dholki-beat Lavani dance performances, and historical warrior pride.',
    hindiDesc: 'मराठी कलात्मक सिनेमा, ढोलकी की थाप पर लावणी नृत्य और ऐतिहासिक शौर्य।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'graceful traditional Maharashtrian Lavani dancer in vibrant Paithani saree, traditional nath nose ring, stage spotlight, 8k render',
      film: 'SCENE DIRECTION: Rhythmic Dholki drum beat drop as Lavani dancer spins in golden stage lights, vibrant cultural heritage celebration.',
      video: 'dynamic cultural dance tracking shot, warm stage illumination, rich Maharashtrian color grade.',
      image_video: 'golden stage glow transition, traditional ornament sparkle, cultural rhythm composite.',
      threeD: 'Paithani saree silk cloth simulation, traditional Maharashtrian theater stage PBR, brass musical instruments.',
    },
    presets: ['Lavani Stage Dholki Dance', 'Historical Fort War Epic', 'Marathi Village Drama', 'Paithani Cultural Fest'],
  },
  {
    id: 'bengali_tollywood_art',
    name: 'Bengali Cinema & Rabindra Sangeet Art',
    hindiName: 'बंगाली सिनेमा व रबीन्द्र संगीत कला',
    category: 'indian_bollywood',
    badge: '🎨 Bengali Cinema',
    emoji: '🎨',
    color: '#3b82f6',
    bgLight: 'bg-blue-500/10',
    borderColor: 'border-blue-500/30',
    description: 'Poetic Kolkata intellectual cinema, soulful Rabindra Sangeet harmonium melodies, Howrah bridge at twilight, and Durga Puja grandeur.',
    hindiDesc: 'कोलकाता की बौद्धिक सिनेमाई कला, रबीन्द्र संगीत, हावड़ा ब्रिज और दुर्गा पूजा।',
    targetStudios: ['image', 'film', 'video', 'image_video', '3d'],
    is18Plus: false,
    promptModifiers: {
      image: 'iconic Howrah Bridge in Kolkata at twilight, yellow taxi cabs, artistic intellectuals drinking tea at roadside stall, cinematic 8k',
      film: 'SCENE DIRECTION: Melancholic poetic tracking shot through North Kolkata vintage alleyway during Durga Puja immersion festival with dhakis beating drums.',
      video: 'poetic slow-pan across Kolkata skyline at sunset, vintage art-house color grading.',
      image_video: 'twilight dhak drum smoke transition, artistic golden hue composite, poetic Kolkata mood.',
      threeD: 'vintage Kolkata street PBR architecture, yellow Ambassador taxi model, Durga Puja pandal decor.',
    },
    presets: ['Howrah Bridge Twilight', 'Durga Puja Dhunuchi Naach', 'Kolkata Coffee House', 'Rabindra Sangeet Poetic'],
  },
];

export function getGenreModifier(genre: ExplicitGenre, studio: StudioTarget): string {
  if (studio === '3d') {
    return genre.promptModifiers.threeD || genre.promptModifiers.image;
  }
  if (studio === 'film') return genre.promptModifiers.film;
  if (studio === 'video') return genre.promptModifiers.video;
  if (studio === 'image_video') return genre.promptModifiers.image_video;
  return genre.promptModifiers.image;
}

/**
 * Apply prompt enhancement for a selected genre and studio
 */
export function applyExplicitEnhancement(
  basePrompt: string,
  genreId: string,
  studio: StudioTarget
): string {
  const genre = EXPLICIT_GENRES.find((g) => g.id === genreId);
  if (!genre) return basePrompt;

  const modifier = getGenreModifier(genre, studio);
  return `${basePrompt.trim()}, ${modifier}`;
}
