import { PersonaType } from '../types.ts';

export interface PersonaPlan {
  id: string;
  name: string;
  hindiName: string;
  price: number;
  durationMonths: number;
  bonusMonths: number;
  tier: 'bronze' | 'silver' | 'gold' | 'diamond';
  popular?: boolean;
  description: string;
  hindiDescription: string;
  tokenBonus: number;
  roleBenefits: string[];
  hasExclusiveContent: boolean;
  exclusiveContentBadge?: string;
}

export const PERSONA_PLANS: Record<PersonaType, PersonaPlan[]> = {
  // 🎓 TEACHER / EDUCATOR PERSONA (शिक्षक व मार्गदर्शक)
  teacher: [
    {
      id: 'teacher_starter_1m',
      name: '1 Month Classroom Starter',
      hindiName: '1 माह कक्षा स्टार्टर',
      price: 249,
      durationMonths: 1,
      bonusMonths: 0,
      tier: 'bronze',
      description: '30 Days Educator Suite • 50+ Lesson Plans & Visual PPTs',
      hindiDescription: '30 दिन शिक्षक सुइट • 50+ पाठ योजनाएं व पीपीटी',
      tokenBonus: 2500,
      roleBenefits: ['Classroom PPT Generator', 'Homework Assistant', 'Watermark-free PDF Export', 'Standard AI Speed'],
      hasExclusiveContent: false,
    },
    {
      id: 'teacher_term_3m',
      name: '3 Months Semester Suite',
      hindiName: '3 माह सेमेस्टर सुइट',
      price: 699,
      durationMonths: 3,
      bonusMonths: 0,
      tier: 'silver',
      description: '90 Days Educator Access • 3D Science Anatomy & Animated Lessons',
      hindiDescription: '90 दिन शिक्षक एक्सेस • 3D विज्ञान एनाटॉमी व एनिमेटेड पाठ',
      tokenBonus: 7500,
      roleBenefits: ['3D Interactive Lab Models', 'Batch Student Worksheet Creation', 'Voice Narration for Lectures', 'Exclusive Educational Content'],
      hasExclusiveContent: true,
      exclusiveContentBadge: 'Exclusive Content (Education & Science)',
    },
    {
      id: 'teacher_pass_6m',
      name: '6 + 1 Month Educator Gold Pass',
      hindiName: '6 + 1 माह शिक्षक गोल्ड पास',
      price: 1299,
      durationMonths: 6,
      bonusMonths: 1,
      tier: 'gold',
      popular: true,
      description: '7 Months Total VIP • Full Unrestricted Video & 8K Visuals + Exclusive Content',
      hindiDescription: '7 माह कुल वीआईपी • असीमित वीडियो व 8K विजुअल्स + एक्सक्लूसिव कंटेंट',
      tokenBonus: 15000,
      roleBenefits: ['Unlimited 4K Classroom Video', 'Unrestricted Exclusive Content', 'Priority GPU Lecture Generation', 'Department Multi-device Sync'],
      hasExclusiveContent: true,
      exclusiveContentBadge: 'Exclusive Content (Unrestricted All Genres)',
    },
    {
      id: 'teacher_titan_12m',
      name: '12 + 2 Months Institution Titan',
      hindiName: '12 + 2 माह संस्थान टाइटन',
      price: 1999,
      durationMonths: 12,
      bonusMonths: 2,
      tier: 'diamond',
      description: '14 Months Complete Academic Titan • Full Studio Suite & Institution License',
      hindiDescription: '14 माह पूर्ण अकादमिक टाइटन • संपूर्ण स्टूडियो सुइट व लाइसेंस',
      tokenBonus: 25000,
      roleBenefits: ['Complete Academic & Creative License', 'All-Genre Exclusive Content & Director Mode', 'Dedicated High-Speed GPU Server', '24/7 Priority Support'],
      hasExclusiveContent: true,
      exclusiveContentBadge: 'Master Exclusive Content Suite',
    },
  ],

  // 🎒 STUDENT / SCHOLAR PERSONA (छात्र व शिक्षार्थी)
  student: [
    {
      id: 'student_budget_1m',
      name: '1 Month Student Scholar Pass',
      hindiName: '1 माह छात्र स्कॉलर पास',
      price: 199,
      durationMonths: 1,
      bonusMonths: 0,
      tier: 'bronze',
      description: '30 Days Student Study Pass • Unlimited Solvers & Concept Summaries',
      hindiDescription: '30 दिन छात्र अध्ययन पास • असीमित नोट्स व अवधारणा समाधान',
      tokenBonus: 2000,
      roleBenefits: ['Exam Revision Notes Generator', 'AI Math & Code Debugger', 'Concept Flashcards & Quizzes', 'Standard Generation Speed'],
      hasExclusiveContent: false,
    },
    {
      id: 'student_exam_3m',
      name: '3 Months Semester Pro',
      hindiName: '3 माह सेमेस्टर प्रो',
      price: 499,
      durationMonths: 3,
      bonusMonths: 0,
      tier: 'silver',
      description: '90 Days Exam Preparation Pass • 3D Chemistry/Physics Lab Visualizer',
      hindiDescription: '90 दिन परीक्षा तैयारी पास • 3D भौतिक/रसायन विज्ञान मॉडल',
      tokenBonus: 5500,
      roleBenefits: ['3D Interactive Concept Models', 'Audio Podcast Study Summaries', 'Project Presentation Builder', 'Exclusive Learning Content'],
      hasExclusiveContent: true,
      exclusiveContentBadge: 'Exclusive Content (Study & 3D Lab)',
    },
    {
      id: 'student_campus_6m',
      name: '6 + 1 Month Campus Champion',
      hindiName: '6 + 1 माह कैंपस चैंपियन',
      price: 899,
      durationMonths: 6,
      bonusMonths: 1,
      tier: 'gold',
      popular: true,
      description: '7 Months Student VIP • Unlimited Video Summaries & Anime/Art Creation',
      hindiDescription: '7 माह छात्र वीआईपी • असीमित वीडियो सारांश व एनीमे निर्माण',
      tokenBonus: 10000,
      roleBenefits: ['Unlimited Presentation Video Renders', 'Anime & Creative Art Engine', 'Exclusive Content Access', 'Priority Student Queue'],
      hasExclusiveContent: true,
      exclusiveContentBadge: 'Exclusive Content (All Creative Genres)',
    },
    {
      id: 'student_titan_12m',
      name: '12 + 2 Months Academic Titan',
      hindiName: '12 + 2 माह अकादमिक टाइटन',
      price: 1599,
      durationMonths: 12,
      bonusMonths: 2,
      tier: 'diamond',
      description: '14 Months Complete Scholar Titan • All 3D, Video, Image & Audio Engines',
      hindiDescription: '14 माह पूर्ण स्कॉलर टाइटन • सभी 3D, वीडियो, इमेज व ऑडियो इंजन',
      tokenBonus: 20000,
      roleBenefits: ['All Academic & Creative Engines', 'Unrestricted Exclusive Content', 'Fastest GPU Rendering Speed', 'Lifetime Project Portfolio'],
      hasExclusiveContent: true,
      exclusiveContentBadge: 'Master Exclusive Content Pass',
    },
  ],

  // 🎬 CONTENT CREATOR PERSONA (डिजिटल क्रिएटर व इन्फ्लुएंसर)
  creator: [
    {
      id: 'creator_starter_1m',
      name: '1 Month Viral Shorts Starter',
      hindiName: '1 माह वायरल शॉर्ट्स स्टार्टर',
      price: 299,
      durationMonths: 1,
      bonusMonths: 0,
      tier: 'bronze',
      description: '30 Days Reels & Shorts Creator • 60 FPS Video & Hook Generator',
      hindiDescription: '30 दिन रील्स व शॉर्ट्स क्रिएटर • 60 FPS वीडियो व हुक जनरेटर',
      tokenBonus: 3500,
      roleBenefits: ['Viral Script & Hook Writer', 'Auto 9:16 Reels Video Renders', 'Voice Narration & Auto-captions', 'Watermark-free Export'],
      hasExclusiveContent: false,
    },
    {
      id: 'creator_pro_3m',
      name: '3 Months YouTube & Reel Pro',
      hindiName: '3 माह यूट्यूब व रील प्रो',
      price: 799,
      durationMonths: 3,
      bonusMonths: 0,
      tier: 'silver',
      description: '90 Days Creator VIP • 4K Video + Voice Cloner + Exclusive Content',
      hindiDescription: '90 दिन क्रिएटर वीआईपी • 4K वीडियो + वॉयस क्लोनर + एक्सक्लूसिव कंटेंट',
      tokenBonus: 9000,
      roleBenefits: ['4K UHD Video Rendering', 'Voice Cloning & Multi-language Dubbing', 'Exclusive Content (All Creator Genres)', 'High-speed GPU Queue'],
      hasExclusiveContent: true,
      exclusiveContentBadge: 'Exclusive Content (Cinematic & Neon)',
    },
    {
      id: 'creator_pass_6m',
      name: '6 + 1 Month Creator Titan Pass',
      hindiName: '6 + 1 माह क्रिएटर टाइटन पास',
      price: 1199,
      durationMonths: 6,
      bonusMonths: 1,
      tier: 'gold',
      popular: true,
      description: '7 Months Unlimited Creator Pass • Full 8K Video + Exclusive Content (18+ & All Genres)',
      hindiDescription: '7 माह असीमित क्रिएटर पास • 8K वीडियो + एक्सक्लूसिव कंटेंट (सभी जोनर)',
      tokenBonus: 15000,
      roleBenefits: ['Unlimited 8K Video & 60 FPS Renders', 'Exclusive Content (Mature, Glamour & Gore 18+)', 'Image+Video Multi-Slot Fusion Mixer', 'Instant Cloud Publishing'],
      hasExclusiveContent: true,
      exclusiveContentBadge: 'Exclusive Content (18+ & Unrestricted All Genres)',
    },
    {
      id: 'creator_titan_12m',
      name: '12 + 2 Months Master Director Titan',
      hindiName: '12 + 2 माह मास्टर डायरेक्टर टाइटन',
      price: 1999,
      durationMonths: 12,
      bonusMonths: 2,
      tier: 'diamond',
      description: '14 Months Ultimate Creator Titan • Full Unrestricted Access & Dedicated GPU Cloud',
      hindiDescription: '14 माह अल्टीमेट क्रिएटर टाइटन • पूर्ण अनसेंसर्ड एक्सेस व क्लाउड जीपीयू',
      tokenBonus: 30000,
      roleBenefits: ['Dedicated 8K Rendering Engine', 'Full Unrestricted Exclusive Content (18+ All Types)', 'Multi-Character Voice Synthesis', 'Commercial Monetization License'],
      hasExclusiveContent: true,
      exclusiveContentBadge: 'VIP Master Unrestricted Exclusive Content',
    },
  ],

  // 💼 STUDIO PROFESSIONAL / VFX (पेशेवर व स्टूडियो आर्टिस्ट)
  professional: [
    {
      id: 'pro_freelancer_1m',
      name: '1 Month Freelancer Pro',
      hindiName: '1 माह फ्रीलांसर प्रो',
      price: 499,
      durationMonths: 1,
      bonusMonths: 0,
      tier: 'bronze',
      description: '30 Days VFX & 3D Pro • 8K Texture Maps & PBR Shaders',
      hindiDescription: '30 दिन वीएफएक्स व 3D प्रो • 8K टेक्सचर मैप्स व शेडर्स',
      tokenBonus: 5000,
      roleBenefits: ['8K PBR Material Generation', '3D Skeletal Auto-Rigging', 'Commercial Client Invoicing', 'Zero Watermark'],
      hasExclusiveContent: false,
    },
    {
      id: 'pro_studio_3m',
      name: '3 Months Commercial Studio',
      hindiName: '3 माह कमर्शियल स्टूडियो',
      price: 999,
      durationMonths: 3,
      bonusMonths: 0,
      tier: 'silver',
      description: '90 Days Commercial Studio • Multi-track Stem Audio + Exclusive Content',
      hindiDescription: '90 दिन कमर्शियल स्टूडियो • मल्टी-ट्रैक स्टेम ऑडियो + एक्सक्लूसिव कंटेंट',
      tokenBonus: 12000,
      roleBenefits: ['Multi-track Audio & Video Fusion', 'Exclusive Content (All Commercial Genres)', 'GLTF / OBJ / FBX 3D Asset Export', 'High-Priority GPU Node'],
      hasExclusiveContent: true,
      exclusiveContentBadge: 'Exclusive Content (Commercial & VFX)',
    },
    {
      id: 'pro_vfx_6m',
      name: '6 + 1 Month VFX Titan Pass',
      hindiName: '6 + 1 माह वीएफएक्स टाइटन पास',
      price: 1499,
      durationMonths: 6,
      bonusMonths: 1,
      tier: 'gold',
      popular: true,
      description: '7 Months VFX Titan • 8K Video + 3D Mesh + Full Unrestricted Exclusive Content',
      hindiDescription: '7 माह वीएफएक्स टाइटन • 8K वीडियो + 3D मेश + पूर्ण एक्सक्लूसिव कंटेंट',
      tokenBonus: 20000,
      roleBenefits: ['8K SSAA 3D Super-sampling Render', 'Exclusive Content (18+ Mature, Anatomy & Horror)', 'Full Screenplay & Multi-scene Direction', 'Enterprise Security & Backup'],
      hasExclusiveContent: true,
      exclusiveContentBadge: 'Exclusive Content (18+ & Fine Art Anatomy)',
    },
    {
      id: 'pro_titan_12m',
      name: '12 + 2 Months Enterprise Titan',
      hindiName: '12 + 2 माह एंटरप्राइज टाइटन',
      price: 1999,
      durationMonths: 12,
      bonusMonths: 2,
      tier: 'diamond',
      description: '14 Months Full Enterprise Suite • Unlimited Generation & Master Creator Rights',
      hindiDescription: '14 माह पूर्ण एंटरप्राइज सुइट • असीमित जेनरेशन व मास्टर राइट्स',
      tokenBonus: 35000,
      roleBenefits: ['Unlimited Concurrent 8K Renders', 'Master Exclusive Content (All 18+ Unrestricted Genres)', 'Full API & Batch Queue Access', 'Dedicated Account Manager'],
      hasExclusiveContent: true,
      exclusiveContentBadge: 'Master Enterprise Exclusive Content',
    },
  ],

  // ✨ GENERAL STUDIO PERSONA (सामान्य स्टूडियो)
  general: [
    {
      id: 'general_starter_1m',
      name: '1 Month Starter Pass',
      hindiName: '1 माह स्टार्टर पास',
      price: 199,
      durationMonths: 1,
      bonusMonths: 0,
      tier: 'bronze',
      description: '30 Days All-Access Starter • Access All Creative Studios',
      hindiDescription: '30 दिन ऑल-एक्सेस स्टार्टर • सभी क्रिएटिव स्टूडियो एक्सेस',
      tokenBonus: 2000,
      roleBenefits: ['Access to Image, Video & Music Studios', 'Basic 3D Model Visualizer', 'Watermark-free Standard Exports', 'Fast Processing'],
      hasExclusiveContent: false,
    },
    {
      id: 'general_pro_3m',
      name: '3 Months All-Studio Pro',
      hindiName: '3 माह ऑल-स्टूडियो प्रो',
      price: 599,
      durationMonths: 3,
      bonusMonths: 0,
      tier: 'silver',
      description: '90 Days All-Studio Pro • 4K Rendering + Exclusive Content',
      hindiDescription: '90 दिन ऑल-स्टूडियो प्रो • 4K रेंडरिंग + एक्सक्लूसिव कंटेंट',
      tokenBonus: 6500,
      roleBenefits: ['4K Image & Video Generation', 'Exclusive Content (Cinematic, Anime & Fantasy)', 'Screenplay Scriptwriting Engine', 'Priority GPU Processing'],
      hasExclusiveContent: true,
      exclusiveContentBadge: 'Exclusive Content (General Genres)',
    },
    {
      id: 'general_creator_6m',
      name: '6 + 1 Month Creative Gold Pass',
      hindiName: '6 + 1 माह क्रिएटिव गोल्ड पास',
      price: 1199,
      durationMonths: 6,
      bonusMonths: 1,
      tier: 'gold',
      popular: true,
      description: '7 Months Total VIP • Unlimited Video Duration + Full Exclusive Content (All Genres)',
      hindiDescription: '7 माह कुल वीआईपी • असीमित वीडियो अवधि + पूर्ण एक्सक्लूसिव कंटेंट',
      tokenBonus: 15000,
      roleBenefits: ['Unlimited Video & Music Duration', 'Exclusive Content (18+ & Unrestricted All Genres)', '3D Auto-Rigging & Emote Studio', 'Commercial Usage Rights'],
      hasExclusiveContent: true,
      exclusiveContentBadge: 'Exclusive Content (18+ Unrestricted All Genres)',
    },
    {
      id: 'general_titan_12m',
      name: '12 + 2 Months Creative Titan',
      hindiName: '12 + 2 माह क्रिएटिव टाइटन',
      price: 1999,
      durationMonths: 12,
      bonusMonths: 2,
      tier: 'diamond',
      description: '14 Months Complete Studio Titan • Unrestricted Master Access Across All Engines',
      hindiDescription: '14 माह पूर्ण स्टूडियो टाइटन • सभी इंजनों पर मास्टर एक्सेस',
      tokenBonus: 25000,
      roleBenefits: ['Unlimited 8K Video & 3D Render', 'Master Exclusive Content (All 18+ Genres & Presets)', 'Priority VIP Server Access', 'Lifetime Archive Storage'],
      hasExclusiveContent: true,
      exclusiveContentBadge: 'Master Exclusive Content Pass',
    },
  ],

  // 👤 GUEST SANDBOX PERSONA (अतिथि खाता - Free Tier)
  guest: [
    {
      id: 'guest_instant_unlock_1m',
      name: 'Instant Account Unlock (1 Month)',
      hindiName: 'इंस्टेंट खाता अनलॉक (1 माह)',
      price: 199,
      durationMonths: 1,
      bonusMonths: 0,
      tier: 'bronze',
      description: '30 Days Full Account • Remove Guest Limits & Unlock All Studios',
      hindiDescription: '30 दिन पूर्ण खाता • गेस्ट सीमाएं हटाएं व सभी स्टूडियो अनलॉक करें',
      tokenBonus: 2000,
      roleBenefits: ['Remove All Guest Sandbox Limits', 'Access to All 7 Creative Studios', 'Watermark-free Downloads', 'Save Custom Profiles'],
      hasExclusiveContent: false,
    },
    {
      id: 'guest_explorer_3m',
      name: '3 Months VIP Explorer',
      hindiName: '3 माह वीआईपी एक्सप्लोरर',
      price: 499,
      durationMonths: 3,
      bonusMonths: 0,
      tier: 'silver',
      description: '90 Days VIP Explorer • 4K Renders + Exclusive Content',
      hindiDescription: '90 दिन वीआईपी एक्सप्लोरर • 4K रेंडर्स + एक्सक्लूसिव कंटेंट',
      tokenBonus: 6000,
      roleBenefits: ['4K Video & High-Res Image Generation', 'Exclusive Content (All Creative Genres)', 'Cloud Storage for Projects', 'Priority Generation Queue'],
      hasExclusiveContent: true,
      exclusiveContentBadge: 'Exclusive Content (General & Creative)',
    },
    {
      id: 'guest_all_access_6m',
      name: '6 + 1 Month All-Access VIP',
      hindiName: '6 + 1 माह ऑल-एक्सेस वीआईपी',
      price: 1199,
      durationMonths: 6,
      bonusMonths: 1,
      tier: 'gold',
      popular: true,
      description: '7 Months Complete VIP • Full Unrestricted Video & Exclusive Content (18+ Included)',
      hindiDescription: '7 माह पूर्ण वीआईपी • असीमित वीडियो व एक्सक्लूसिव कंटेंट (18+ शामिल)',
      tokenBonus: 15000,
      roleBenefits: ['Unlimited Video & 3D WebGL Rendering', 'Exclusive Content (18+ Unrestricted All Genres)', 'Custom Sub-profile Management', 'Commercial Export Rights'],
      hasExclusiveContent: true,
      exclusiveContentBadge: 'Exclusive Content (18+ Unrestricted All Genres)',
    },
    {
      id: 'guest_titan_12m',
      name: '12 + 2 Months Ultimate Titan',
      hindiName: '12 + 2 माह अल्टीमेट टाइटन',
      price: 1999,
      durationMonths: 12,
      bonusMonths: 2,
      tier: 'diamond',
      description: '14 Months Complete Titan • Highest GPU Priority & Master Access',
      hindiDescription: '14 माह पूर्ण टाइटन • उच्चतम जीपीयू प्राथमिकता व मास्टर एक्सेस',
      tokenBonus: 25000,
      roleBenefits: ['All 7 Creative Studios Unlocked', 'Master Exclusive Content (All Genres 18+)', 'Dedicated GPU Cluster Access', '24/7 Priority Support'],
      hasExclusiveContent: true,
      exclusiveContentBadge: 'Master Exclusive Content Pass',
    },
  ],
};

export function getPlansForPersona(persona?: PersonaType): PersonaPlan[] {
  const safePersona = persona && PERSONA_PLANS[persona] ? persona : 'general';
  return PERSONA_PLANS[safePersona];
}
