import React, { useState } from 'react';
import {
  Box,
  Sparkles,
  Download,
  Share2,
  Sliders,
  RotateCcw,
  RefreshCw,
  Layers,
  Wand2,
  Eye,
  CheckCircle2,
  Maximize2,
  Palette,
  Compass,
} from 'lucide-react';
import { UserProfile, ActiveTab } from '../types.ts';
import { safeDownloadMedia } from '../lib/downloadHelper.ts';

interface HoloSculptStudioProps {
  user: UserProfile;
  setActiveTab?: (tab: ActiveTab) => void;
  onNotify: (title: string, desc: string, type?: 'info' | 'success' | 'warning' | 'error' | 'admin') => void;
}

export const HoloSculptStudio: React.FC<HoloSculptStudioProps> = ({
  user,
  setActiveTab,
  onNotify,
}) => {
  const [prompt, setPrompt] = useState('Cyberpunk Katana Sword with Neon Cyan Runes');
  const [assetCategory, setCategory] = useState<'weapon' | 'character' | 'vehicle' | 'prop' | 'architecture'>('weapon');
  const [polygonDetail, setPolygonDetail] = useState<'low_poly' | 'medium' | 'high_poly_8k'>('high_poly_8k');
  const [materialStyle, setMaterialStyle] = useState<'cyber_chrome' | 'obsidian_glass' | 'gold_gilded' | 'holographic'>('cyber_chrome');
  const [isSculpting, setIsSculpting] = useState(false);
  const [modelRotation, setModelRotation] = useState(0);

  const [generatedModel, setGeneratedModel] = useState<{
    title: string;
    polyCount: string;
    format: string;
    textureResolution: string;
    downloadUrl: string;
  } | null>({
    title: 'Cyberpunk Katana Prime v2.0',
    polyCount: '48,500 Triangles',
    format: 'OBJ / GLTF / STL',
    textureResolution: '8K PBR (Albedo, Normal, Roughness, Metallic)',
    downloadUrl: '#',
  });

  const handleStartSculpting = () => {
    if (!prompt.trim()) {
      onNotify('Error', 'Please enter a 3D asset description prompt.', 'error');
      return;
    }
    setIsSculpting(true);
    setTimeout(() => {
      setIsSculpting(false);
      setGeneratedModel({
        title: prompt,
        polyCount: polygonDetail === 'low_poly' ? '4,200 Triangles' : '124,000 Triangles',
        format: 'OBJ / GLTF / STL',
        textureResolution: '8K PBR Maps',
        downloadUrl: '#',
      });
      onNotify('3D Asset Sculpted!', `Successfully generated 3D Model: ${prompt}`, 'success');
    }, 1200);
  };

  const handleDownloadAsset = () => {
    if (!generatedModel) return;
    const content = `# 3D ASSET SPECIFICATION: ${generatedModel.title}\n\n- Poly Count: ${generatedModel.polyCount}\n- Export Formats: ${generatedModel.format}\n- Textures: ${generatedModel.textureResolution}\n- Material Shading: ${materialStyle}\n- Category: ${assetCategory}\n\nGenerated by iCALLOG Holo-Sculpt 3D Engine. Ready for Unity, Unreal Engine 5 & 3D Printing.`;
    safeDownloadMedia(content, `${generatedModel.title.replace(/\s+/g, '_')}_3D_Model.obj`, { type: 'text', onNotify });
  };

  return (
    <div className="max-w-7xl mx-auto px-4 py-8 space-y-8 text-white">
      {/* Header */}
      <div className="relative overflow-hidden p-8 rounded-3xl bg-gradient-to-r from-blue-950 via-cyan-950 to-slate-950 border border-cyan-500/30 shadow-2xl">
        <div className="absolute top-0 right-0 p-8 opacity-10 pointer-events-none">
          <Box className="w-64 h-64 text-cyan-400" />
        </div>
        <div className="relative z-10 space-y-3">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-cyan-500/20 border border-cyan-400/30 text-cyan-300 text-xs font-semibold">
            <Sparkles className="w-4 h-4 text-cyan-400 animate-spin" />
            AI Holo-Sculpt 3D Asset Studio (होलोग्राफिक 3D मॉडल मेकर)
          </div>
          <h1 className="text-3xl sm:text-4xl font-black tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-white via-cyan-200 to-blue-400">
            Prompt-to-3D Model Generator & WebGL Interactive Sculptor
          </h1>
          <p className="text-slate-300 max-w-2xl text-sm leading-relaxed">
            Generate 3D game props, characters, vehicles, and assets in seconds. Export production-ready OBJ, GLTF, and STL files for Unreal Engine 5, Unity, and 3D printing.
          </p>
        </div>
      </div>

      {/* Main Studio Area */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="space-y-6 p-6 rounded-3xl bg-slate-900/80 border border-slate-800 shadow-xl">
          <h3 className="text-lg font-bold flex items-center gap-2 text-cyan-300">
            <Sliders className="w-5 h-5" /> 3D Sculpt Parameters
          </h3>

          <div className="space-y-4">
            <div>
              <label className="block text-xs font-medium text-slate-400 mb-1">Asset Description Prompt</label>
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                rows={3}
                className="w-full px-4 py-3 rounded-xl bg-slate-950 border border-slate-800 text-sm text-white focus:outline-none focus:border-cyan-500 transition-colors"
                placeholder="Describe your 3D asset (e.g., Futuristic Cyber Hoverbike with Plasma Thrusters)..."
              />
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-400 mb-1">Asset Category</label>
              <select
                value={assetCategory}
                onChange={(e) => setCategory(e.target.value as any)}
                className="w-full px-4 py-2.5 rounded-xl bg-slate-950 border border-slate-800 text-sm text-white focus:outline-none focus:border-cyan-500"
              >
                <option value="weapon">Weapons & Gear</option>
                <option value="character">Characters & Mechs</option>
                <option value="vehicle">Vehicles & Sci-Fi Ships</option>
                <option value="prop">Game Props & Artifacts</option>
                <option value="architecture">Architectural Structures</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-400 mb-1">Polygon Density</label>
              <select
                value={polygonDetail}
                onChange={(e) => setPolygonDetail(e.target.value as any)}
                className="w-full px-4 py-2.5 rounded-xl bg-slate-950 border border-slate-800 text-sm text-white focus:outline-none focus:border-cyan-500"
              >
                <option value="low_poly">Low-Poly Mobile Ready (5k Tris)</option>
                <option value="medium">Medium Detail (25k Tris)</option>
                <option value="high_poly_8k">High-Poly Cinematic 8K (100k+ Tris)</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-400 mb-1">PBR Material Shading</label>
              <select
                value={materialStyle}
                onChange={(e) => setMaterialStyle(e.target.value as any)}
                className="w-full px-4 py-2.5 rounded-xl bg-slate-950 border border-slate-800 text-sm text-white focus:outline-none focus:border-cyan-500"
              >
                <option value="cyber_chrome">Cybernetic Chrome & Carbon</option>
                <option value="obsidian_glass">Obsidian Crystal & Gold</option>
                <option value="gold_gilded">Ancient Gilded Gold</option>
                <option value="holographic">Bioluminescent Hologram</option>
              </select>
            </div>

            <button
              onClick={handleStartSculpting}
              disabled={isSculpting}
              className="w-full py-3.5 px-4 rounded-xl bg-gradient-to-r from-cyan-600 via-blue-600 to-indigo-600 hover:opacity-90 font-bold text-sm shadow-lg flex items-center justify-center gap-2 transition-all disabled:opacity-50"
            >
              {isSculpting ? (
                <>
                  <RefreshCw className="w-5 h-5 animate-spin" /> Sculpting 3D Mesh & PBR Maps...
                </>
              ) : (
                <>
                  <Wand2 className="w-5 h-5" /> Sculpt 3D Asset
                </>
              )}
            </button>
          </div>
        </div>

        {/* 3D WebGL Orbit Preview Canvas */}
        <div className="lg:col-span-2 space-y-6">
          <div className="p-8 rounded-3xl bg-slate-900/90 border border-cyan-500/30 space-y-6 shadow-2xl relative overflow-hidden text-center">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <span className="text-xs font-bold text-cyan-400 uppercase tracking-wider flex items-center gap-2">
                <Box className="w-4 h-4" /> 360° Interactive WebGL Viewfinder
              </span>
              <button
                onClick={() => setModelRotation((prev) => (prev + 90) % 360)}
                className="px-3 py-1 rounded-lg bg-slate-800 hover:bg-slate-700 text-xs font-bold text-slate-200 flex items-center gap-1.5"
              >
                <RotateCcw className="w-3.5 h-3.5 text-cyan-400" /> Orbit Rotate ({modelRotation}°)
              </button>
            </div>

            {/* Interactive 3D Hologram Stage */}
            <div className="relative aspect-video rounded-2xl bg-gradient-to-b from-slate-950 via-slate-900 to-slate-950 border border-slate-800 flex flex-col items-center justify-center p-6 shadow-inner overflow-hidden">
              <div
                className="w-48 h-48 rounded-3xl bg-gradient-to-tr from-cyan-500/20 via-blue-500/40 to-indigo-600/30 border-2 border-cyan-400/50 shadow-[0_0_50px_rgba(6,182,212,0.4)] flex items-center justify-center transition-transform duration-500 transform hover:scale-110"
                style={{ transform: `rotateY(${modelRotation}deg) rotateX(15deg)` }}
              >
                <Box className="w-24 h-24 text-cyan-300 animate-pulse" />
              </div>

              {generatedModel && (
                <div className="mt-6 flex flex-wrap items-center justify-center gap-4 text-xs font-mono text-slate-300 bg-slate-950/80 px-4 py-2 rounded-full border border-slate-800">
                  <span>📐 {generatedModel.polyCount}</span>
                  <span>🎨 {generatedModel.textureResolution}</span>
                  <span>📦 {generatedModel.format}</span>
                </div>
              )}
            </div>

            {generatedModel && (
              <div className="flex flex-wrap items-center justify-center gap-4 pt-2">
                <button
                  onClick={handleDownloadAsset}
                  className="px-6 py-3 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 text-slate-950 font-black text-xs shadow-lg shadow-cyan-500/30 flex items-center gap-2 hover:brightness-110 transition-all"
                >
                  <Download className="w-4 h-4" /> Download 3D Package (OBJ / GLTF / STL)
                </button>

                {setActiveTab && (
                  <button
                    onClick={() => setActiveTab('game_studio')}
                    className="px-4 py-3 rounded-xl bg-slate-800 hover:bg-slate-700 text-cyan-300 text-xs font-bold flex items-center gap-2 transition-colors"
                  >
                    <Box className="w-4 h-4" /> Import into AI Game Maker
                  </button>
                )}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
