import React, { useState, useEffect } from 'react';
import {
  Sparkles,
  Zap,
  Play,
  Film,
  Cpu,
  Bot,
  Download,
  Share2,
  CheckCircle2,
  RefreshCw,
  Sliders,
  Layers,
  Wand2,
  Flame,
  Globe2,
} from 'lucide-react';
import { UserProfile, ActiveTab } from '../types.ts';
import { safeDownloadMedia } from '../lib/downloadHelper.ts';

interface QuantumDirectorStudioProps {
  user: UserProfile;
  setActiveTab?: (tab: ActiveTab) => void;
  onNotify: (title: string, desc: string, type?: 'info' | 'success' | 'warning' | 'error' | 'admin') => void;
}

export const QuantumDirectorStudio: React.FC<QuantumDirectorStudioProps> = ({
  user,
  setActiveTab,
  onNotify,
}) => {
  const [prompt, setPrompt] = useState('An elite cyber-detective discovering a secret portal under Tokyo in 2150');
  const [genre, setGenre] = useState('Cyberpunk Sci-Fi');
  const [style, setStyle] = useState('8K Anamorphic Cinematic');
  const [isGenerating, setIsGenerating] = useState(false);
  const [progressStep, setProgressStep] = useState(0);
  const [generatedResult, setGeneratedResult] = useState<{
    title: string;
    logline: string;
    script: string[];
    visualPrompts: string[];
    audioPrompt: string;
    status: string;
  } | null>(null);

  const steps = [
    'Initializing Quantum AI Autonomous Engine...',
    'Generating 3-Act Narrative Script & Dialogue...',
    'Synthesizing Cinematic Shot-by-Shot Storyboard Prompts...',
    'Composing Dual-Voice AI Narration & Soundtrack...',
    'Rendering Final Masterpiece Video Stream & Metadata...',
  ];

  const handleStartAutopilot = () => {
    if (!prompt.trim()) {
      onNotify('Error', 'Please enter a creative premise or logline.', 'error');
      return;
    }

    setIsGenerating(true);
    setProgressStep(0);

    let current = 0;
    const interval = setInterval(() => {
      current++;
      if (current < steps.length) {
        setProgressStep(current);
      } else {
        clearInterval(interval);
        setIsGenerating(false);
        setGeneratedResult({
          title: 'Chronicles of the Deep Cyber Portal: Episode I',
          logline: prompt,
          script: [
            'INT. TOKYO SUB-LEVEL 9 - NIGHT (2150)',
            'Neon cyan rain trickles down through grated titanium bulkheads. Detective Kairen steps forward, his ocular implants flickering with warning alerts.',
            'KAIREN (V.O.)',
            'They told us the lower sectors were abandoned. They lied. The grid is breathing.',
            'A massive holographic gateway ignites in front of him, revealing ancient stellar coordinates leading deep into the Andromeda void.',
          ],
          visualPrompts: [
            'Wide cinematic establishing shot of submerged neon Tokyo cyberpunk undercity, 2.39:1 anamorphic ratio',
            'Close-up on cybernetic detective eyes glowing cyan, reflecting code streams',
            'Epic ancient stellar portal opening with gravitational distortions and bioluminescent particle fx',
          ],
          audioPrompt: 'Heavy synth-wave bassline with low sub-frequencies, emotional ethereal choir and ambient rain soundscape',
          status: 'Successfully Generated by Quantum AI Director',
        });
        onNotify('Quantum Success!', 'Autonomous AI Director has successfully produced your film masterwork!', 'success');
      }
    }, 1200);
  };

  const handleDownloadPackage = () => {
    if (!generatedResult) return;
    const content = `# ${generatedResult.title}\n\nLOGLINE:\n${generatedResult.logline}\n\nSCRIPT:\n${generatedResult.script.join('\n')}\n\nVISUAL SHOTS:\n${generatedResult.visualPrompts.join('\n')}\n\nAUDIO CUE:\n${generatedResult.audioPrompt}`;
    safeDownloadMedia(content, 'Quantum_AI_Film_Production_Package.md', { type: 'text', onNotify });
  };

  return (
    <div className="max-w-7xl mx-auto px-4 py-8 space-y-8 text-white">
      {/* Header */}
      <div className="relative overflow-hidden p-8 rounded-3xl bg-gradient-to-r from-indigo-950 via-purple-950 to-slate-950 border border-indigo-500/30 shadow-2xl">
        <div className="absolute top-0 right-0 p-8 opacity-10 pointer-events-none">
          <Bot className="w-64 h-64 text-indigo-400" />
        </div>
        <div className="relative z-10 space-y-3">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-indigo-500/20 border border-indigo-400/30 text-indigo-300 text-xs font-semibold">
            <Sparkles className="w-4 h-4 text-indigo-400 animate-spin" />
            Quantum AI Autonomous Director (ऑटोनॉमस एआई डायरेक्टर)
          </div>
          <h1 className="text-3xl sm:text-4xl font-black tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-white via-indigo-200 to-indigo-400">
            1-Click AI Auto-Movie Producer & Script-to-Screen Engine
          </h1>
          <p className="text-slate-300 max-w-2xl text-sm leading-relaxed">
            Type any one-liner premise and watch our autonomous neural agent generate the full script, storyboards, voiceover prompts, and cinematic score instantly.
          </p>
        </div>
      </div>

      {/* Main Control Panel */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-1 space-y-6 p-6 rounded-3xl bg-slate-900/80 border border-slate-800 shadow-xl">
          <h3 className="text-lg font-bold flex items-center gap-2 text-indigo-300">
            <Sliders className="w-5 h-5" /> Directorial Parameters
          </h3>

          <div className="space-y-4">
            <div>
              <label className="block text-xs font-medium text-slate-400 mb-1">Movie / Video Premise (लॉगलाइन)</label>
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                rows={3}
                className="w-full px-4 py-3 rounded-xl bg-slate-950 border border-slate-800 text-sm text-white focus:outline-none focus:border-indigo-500 transition-colors"
                placeholder="Describe your film or viral video idea..."
              />
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-400 mb-1">Genre</label>
              <select
                value={genre}
                onChange={(e) => setGenre(e.target.value)}
                className="w-full px-4 py-2.5 rounded-xl bg-slate-950 border border-slate-800 text-sm text-white focus:outline-none focus:border-indigo-500"
              >
                <option value="Cyberpunk Sci-Fi">Cyberpunk Sci-Fi</option>
                <option value="Epic Fantasy Adventure">Epic Fantasy Adventure</option>
                <option value="Psychological Thriller">Psychological Thriller</option>
                <option value="Bollywood Romantic Drama">Bollywood Romantic Drama</option>
                <option value="Cosmic Documentary">Cosmic Documentary</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-400 mb-1">Cinematic Style</label>
              <select
                value={style}
                onChange={(e) => setStyle(e.target.value)}
                className="w-full px-4 py-2.5 rounded-xl bg-slate-950 border border-slate-800 text-sm text-white focus:outline-none focus:border-indigo-500"
              >
                <option value="8K Anamorphic Cinematic">8K Anamorphic Cinematic</option>
                <option value="IMAX 70mm Epic">IMAX 70mm Epic</option>
                <option value="Gritty Neo-Noir Grain">Gritty Neo-Noir Grain</option>
                <option value="Hyper-Realistic Anime">Hyper-Realistic Anime</option>
              </select>
            </div>

            <button
              onClick={handleStartAutopilot}
              disabled={isGenerating}
              className="w-full py-3.5 px-4 rounded-xl bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 hover:opacity-90 font-bold text-sm shadow-lg flex items-center justify-center gap-2 transition-all disabled:opacity-50"
            >
              {isGenerating ? (
                <>
                  <RefreshCw className="w-5 h-5 animate-spin" /> Directing Masterpiece...
                </>
              ) : (
                <>
                  <Wand2 className="w-5 h-5" /> Start Quantum Auto-Direction
                </>
              )}
            </button>
          </div>
        </div>

        {/* Output Area */}
        <div className="lg:col-span-2 space-y-6">
          {isGenerating && (
            <div className="p-8 rounded-3xl bg-slate-900/90 border border-indigo-500/30 text-center space-y-6 shadow-2xl">
              <div className="relative w-20 h-20 mx-auto">
                <div className="absolute inset-0 rounded-full border-4 border-indigo-500/20 border-t-indigo-500 animate-spin" />
                <Bot className="absolute inset-0 m-auto w-8 h-8 text-indigo-400" />
              </div>
              <div className="space-y-2">
                <h4 className="text-lg font-bold text-indigo-300">{steps[progressStep]}</h4>
                <p className="text-xs text-slate-400">Autonomous Neural Agents are rendering your production package...</p>
              </div>
              <div className="w-full bg-slate-950 rounded-full h-2.5 max-w-md mx-auto overflow-hidden">
                <div
                  className="bg-gradient-to-r from-indigo-500 to-pink-500 h-2.5 transition-all duration-500 rounded-full"
                  style={{ width: `${((progressStep + 1) / steps.length) * 100}%` }}
                />
              </div>
            </div>
          )}

          {!isGenerating && !generatedResult && (
            <div className="p-12 rounded-3xl bg-slate-900/50 border border-slate-800 text-center space-y-4">
              <Film className="w-16 h-16 text-slate-600 mx-auto" />
              <h3 className="text-lg font-bold text-slate-300">Awaiting Quantum Director Input</h3>
              <p className="text-xs text-slate-500 max-w-md mx-auto">
                Configure your premise on the left and click 'Start Quantum Auto-Direction' to generate an entire film production blueprint in seconds.
              </p>
            </div>
          )}

          {!isGenerating && generatedResult && (
            <div className="p-6 rounded-3xl bg-slate-900/90 border border-indigo-500/40 space-y-6 shadow-2xl">
              <div className="flex items-center justify-between border-b border-slate-800 pb-4">
                <div>
                  <div className="flex items-center gap-2 text-indigo-400 text-xs font-semibold mb-1">
                    <CheckCircle2 className="w-4 h-4" /> {generatedResult.status}
                  </div>
                  <h2 className="text-xl font-black text-white">{generatedResult.title}</h2>
                </div>
                <div className="flex items-center gap-3">
                  <button
                    onClick={handleDownloadPackage}
                    className="px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-xs font-bold flex items-center gap-2 shadow-md transition-colors"
                  >
                    <Download className="w-4 h-4" /> Download Script & Package
                  </button>
                  {setActiveTab && (
                    <button
                      onClick={() => setActiveTab('film_studio')}
                      className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-xs font-bold flex items-center gap-2 transition-colors"
                    >
                      <Film className="w-4 h-4" /> Open Film Studio
                    </button>
                  )}
                </div>
              </div>

              <div className="space-y-4">
                <div>
                  <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Logline</h4>
                  <p className="text-sm text-slate-200 bg-slate-950 p-3.5 rounded-xl border border-slate-800">
                    {generatedResult.logline}
                  </p>
                </div>

                <div>
                  <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Generated 3-Act Script</h4>
                  <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 space-y-2 font-mono text-xs text-indigo-200 max-h-48 overflow-y-auto">
                    {generatedResult.script.map((line, idx) => (
                      <p key={idx} className={line.includes('(V.O.)') || line.includes('INT.') ? 'text-amber-300 font-bold' : ''}>
                        {line}
                      </p>
                    ))}
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Visual Storyboard Prompts</h4>
                    <ul className="space-y-1.5 text-xs text-slate-300 bg-slate-950 p-3.5 rounded-xl border border-slate-800">
                      {generatedResult.visualPrompts.map((vp, idx) => (
                        <li key={idx} className="flex items-start gap-2">
                          <span className="text-indigo-400 font-bold">#{idx + 1}</span> {vp}
                        </li>
                      ))}
                    </ul>
                  </div>
                  <div>
                    <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Soundtrack & Audio Cue</h4>
                    <p className="text-xs text-slate-300 bg-slate-950 p-3.5 rounded-xl border border-slate-800 h-full">
                      🎵 {generatedResult.audioPrompt}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
